### ISSUE TITLE
This is crazy 😂

### ISSUE THREAD

**Issue by rami-maalouf** [Axorax/socials#2]
If you're wondering how I landed here, here's how:
Found your website appembed [here](https://stacksorted.com/buttons/app-embed). Arrived there from the design but stayed there for the usefulness. From there I wanted to look at the code for the website and the developer and that's how I landed on your github and then I land on this repo and holy shit that's A LOT OF SOCIALS

Anyways just wanted to say keep doing random stuff, one day you'll solve a "random" problem everyone faces and as a result your software will positively impact millions of people's lives

Somehow you have like 50 socials but not linkedin lol. If you ever create a linkedin account, [connect with me](https://www.linkedin.com/in/rami--maalouf/)

**Comment by Axorax** [comment]
Thanks!
